server:
  port: 8100
  tomcat:
      uri-encoding: UTF-8
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://120.24.5.178:3306/loginDemo?useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: li197910
  http:
      encoding:
        charset: utf-8
        enabled: true
  jpa:
     hibernate:
       ddl-auto: update
#       ddl-auto: create 每次都新建表 update 更新数据 validate 验证标结构属性是否一致
     show-sql: true
